var a = [
    {
      sku: "1525813598",
      idProduto: "37857672",
      nome: "cozinha compacta com armario e balcao mp2002 sofia multimo" +
            "veis preta",
      lista: "resultado-busca",
      posicao: "1",
      disponibilidadeEstoque: "disponivel",
      preco: 251.36,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "multimoveis",
      idMarca: "806",
      variacao: "preto"
    },
    {
      sku: "15179898",
      idProduto: "11584240",
      nome: "cozinha compacta emilly pop com armario e balcao",
      lista: "resultado-busca",
      posicao: "2",
      disponibilidadeEstoque: "disponivel",
      preco: 489.99,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "madesa",
      idMarca: "314",
      variacao: "marrom"
    },
    {
      sku: "1504991784",
      idProduto: "17011934",
      nome: "armario de cozinha 8 portas 2 gavetas onix chf branco",
      lista: "resultado-busca",
      posicao: "3",
      disponibilidadeEstoque: "disponivel",
      preco: 339.91,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "nao informado",
      idMarca: "13181",
      variacao: "branco"
    },
    {
      sku: "1525437968",
      idProduto: "37482110",
      nome: "cozinha compacta 4 pc c armario e balcao mp3691 veneza gb " +
            "preta",
      lista: "resultado-busca",
      posicao: "4",
      disponibilidadeEstoque: "disponivel",
      preco: 764.23,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "multimoveis",
      idMarca: "806",
      variacao: "preto"
    },
    {
      sku: "1500565524",
      idProduto: "12450046",
      nome: "armario de cozinha completa genova nogueira off white",
      lista: "resultado-busca",
      posicao: "5",
      disponibilidadeEstoque: "disponivel",
      preco: 402.69,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "kits parana",
      idMarca: "14528",
      variacao: "marrom cacau"
    },
    {
      sku: "1500934943",
      idProduto: "12789993",
      nome: "cozinha completa madesa diamante com armario balcao e tamp" +
            "o branco",
      lista: "resultado-busca",
      posicao: "6",
      disponibilidadeEstoque: "disponivel",
      preco: 839.99,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "madesa",
      idMarca: "314",
      variacao: "branco"
    },
    {
      sku: "1504721405",
      idProduto: "16741325",
      nome: "armario de cozinha completa golden nogueira off white",
      lista: "resultado-busca",
      posicao: "7",
      disponibilidadeEstoque: "disponivel",
      preco: 279,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "nao informada",
      idMarca: "190821",
      variacao: "palha"
    },
    {
      sku: "1504935322",
      idProduto: "16955477",
      nome: "armario de cozinha completa compacta com 12 portas clara c" +
            "arvalho branco",
      lista: "resultado-busca",
      posicao: "8",
      disponibilidadeEstoque: "disponivel",
      preco: 549,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "poliman moveis",
      idMarca: "33621",
      variacao: "branco"
    },
    {
      sku: "1509310180",
      idProduto: "21358322",
      nome: "armario de cozinha completa com 12 portas clara branco",
      lista: "resultado-busca",
      posicao: "9",
      disponibilidadeEstoque: "disponivel",
      preco: 487.2,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "poliman moveis",
      idMarca: "33621",
      variacao: "branco"
    },
    {
      sku: "1512965671",
      idProduto: "25014902",
      nome: "cozinha compacta c armario e balcao com tampo pequim up mu" +
            "ltimoveis pretalacca fume",
      lista: "resultado-busca",
      posicao: "10",
      disponibilidadeEstoque: "disponivel",
      preco: 456.93,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "multimoveis",
      idMarca: "806",
      variacao: "preto"
    },
    {
      sku: "1505072323",
      idProduto: "17092289",
      nome: "cozinha completa c armario e balcao xangai jazz multimoveis",
      lista: "resultado-busca",
      posicao: "11",
      disponibilidadeEstoque: "disponivel",
      preco: 692.62,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "multimoveis",
      idMarca: "806"
    },
    {
      sku: "1527177716",
      idProduto: "39221725",
      nome: "armario de cozinha suspenso 7 portas e 2 gavetas juliete c" +
            "arvalho cinza nicioli",
      lista: "resultado-busca",
      posicao: "12",
      disponibilidadeEstoque: "disponivel",
      preco: 437.07,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "nicioli",
      idMarca: "1855",
      variacao: "cinza"
    },
    {
      sku: "1519057499",
      idProduto: "31106973",
      nome: "armario de cozinha compacta madesa emilly pop com balcao r" +
            "usticbranco",
      lista: "resultado-busca",
      posicao: "13",
      disponibilidadeEstoque: "disponivel",
      preco: 719.99,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "madesa",
      idMarca: "314",
      variacao: "marrom"
    },
    {
      sku: "1525812805",
      idProduto: "37856883",
      nome: "cozinha compacta com armario e balcao mp2004 sofia multimo" +
            "veis preta",
      lista: "resultado-busca",
      posicao: "14",
      disponibilidadeEstoque: "disponivel",
      preco: 259.94,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "multimoveis",
      idMarca: "806",
      variacao: "preto"
    },
    {
      sku: "1509466989",
      idProduto: "21515221",
      nome: "kit cozinha mirela 7 portas e 3 gavetas atacamaoff white",
      lista: "resultado-busca",
      posicao: "15",
      disponibilidadeEstoque: "disponivel",
      preco: 710.81,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "aramoveis",
      idMarca: "9870",
      variacao: "bege claro"
    },
    {
      sku: "1517373927",
      idProduto: "29420411",
      nome: "armario de cozinha galicia 4 pcs 3 portas borepret moveis " +
            "arapongas",
      lista: "resultado-busca",
      posicao: "16",
      disponibilidadeEstoque: "disponivel",
      preco: 345.68,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "moveis arapongas",
      idMarca: "171278",
      variacao: "marrom"
    },
    {
      sku: "1540053698",
      idProduto: "51489957",
      nome: "armario de cozinha modulada tieli 4 pecas preto fosco move" +
            "is arapongas",
      lista: "resultado-busca",
      posicao: "17",
      disponibilidadeEstoque: "disponivel",
      preco: 629.25,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "moveis arapongas",
      idMarca: "171278",
      variacao: "preto"
    },
    {
      sku: "13693151",
      idProduto: "10110716",
      nome: "kit cozinha viena plus 1200 madine moveis",
      lista: "resultado-busca",
      posicao: "18",
      disponibilidadeEstoque: "disponivel",
      preco: 396.61,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "nao informado",
      idMarca: "13181"
    },
    {
      sku: "1525437742",
      idProduto: "37481884",
      nome: "cozinha compacta 2 pc c armario e balcao mp3687 veneza gb " +
            "preta",
      lista: "resultado-busca",
      posicao: "19",
      disponibilidadeEstoque: "disponivel",
      preco: 433.29,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "multimoveis",
      idMarca: "806",
      variacao: "preto"
    },
    {
      sku: "1502840900",
      idProduto: "14863240",
      nome: "cozinha completa madesa reims xa260001 com armario e balca" +
            "o pretorustic",
      lista: "resultado-busca",
      posicao: "20",
      disponibilidadeEstoque: "disponivel",
      preco: 832.99,
      idDepartamento: "93",
      nomeDepartamento: "moveis",
      idLinha: "693",
      nomeLinha: "cozinhas",
      idSubLinha: "698",
      nomeSubLinha: "cozinha compacta",
      nomeMarca: "madesa",
      idMarca: "314",
      variacao: "preto"
    }
  ]

function skuFunc(a){
    for(var i = 0; i < a.length; i++){
        var b = b || []
        b.push(a[i].sku)
    }
    b = b.toString();
    return b
}
console.log(skuFunc(a))